name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Install dependencies
        run: yarn install
      - name: Release NPM Registry
        env:
          GIT_AUTHOR_NAME: "@bumper-bot"
          GITHUB_TOKEN: ${{ secrets.GH_MASTER_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GH_MASTER_TOKEN }}
        run: |
          yarn build
          yarn release
      - name: Release GitHub Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MASTER_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GH_MASTER_TOKEN }}
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > ~/.npmrc
          yarn release:github_registry
